#!/bin/bash

CONTAINER_NAME="backbone-server"
PORT_HOST=9999
DB_DIRECTORY="/Users/lap00344/MyProject/database"

if [ -z $1 ]; then
    echo -e "Supported arguments:
        * help
        * docker [start|ssh|cmd|compose]
    "
elif [ "$1" == "help" ]; then
    echo "Docker config"
    echo "Container: $CONTAINER_NAME"
    echo "DB directory: $DB_DIRECTORY"
    echo "Port host: $PORT_HOST"
    echo
    echo "docker rmi devhoanggia/docker-wordpress"
    echo "docker inspect $CONTAINER_NAME"
    echo "docker logs $CONTAINER_NAME"
    echo "docker pull devhoanggia/docker-wordpress"

elif [ "$1" == "docker" ]; then
    if [ -z $2 ]; then
        echo -e "Available options:
            * start
            * ssh
            * cmd
            * compose
        "
    elif [ "$2" == "start" ]; then
        docker pull devhoanggia/docker-wordpress

        if docker ps -a | grep -qs $CONTAINER_NAME; then
            echo "Removing intermediate container $CONTAINER_NAME"
            docker rm -f $CONTAINER_NAME
        fi

        if docker ps -a | grep -qs mysql; then
            echo "Removing intermediate container mysql"
            docker rm -f mysql
        fi

        echo "Creating container mysql"
        docker run --name mysql -d -p 8888:3306 -v $DB_DIRECTORY:/store/db devhoanggia/docker-mysql

        echo "Creating container $CONTAINER_NAME"
        docker run --name $CONTAINER_NAME -d -p $PORT_HOST:80 -v `pwd`:/var/www/html --link mysql:mysql devhoanggia/docker-wordpress

        echo "http://localhost:$PORT_HOST"
    elif [ "$2" == "ssh" ]; then
        docker exec -it $CONTAINER_NAME bash
    fi
else
    if docker ps -a | grep -qs $CONTAINER_NAME; then
        docker exec -it $CONTAINER_NAME bash -c "cd /var/www/html; $*"
    else
        echo "Please start the container first!"
        exit
    fi
fi